### PR TITLE
WL-3835: Change to clearer 'Add Assignment' labels

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Adam wanted to fix this Jira our way and comment on the alternative Sakai Jira fix and see what happens there...

**Comment by buckett** [comment]
This now won't match the help.

**Comment by nicholaswilson100** [comment]
https://github.com/ox-it/wl-help/pull/10

**Comment by nicholaswilson100** [comment]
Linked to help pull request

**Pull request merged**
